# Generated by Django 4.0.1 on 2022-02-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='bookFor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.room'),
        ),
    ]
