# Generated by Django 4.0.1 on 2022-02-02 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookuser_bookfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuser',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
